/*
 * This source file was generated by the Gradle 'init' task
 */
package org.control;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ManagerTest {
    @Test void ManagerHasAGreeting() {
        Manager classUnderTest = new Manager();
        assertNotNull(classUnderTest.getGreeting(), "Manager should have a greeting");
    }
}
